In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [3]:
from sklearn.model_selection import cross_val_score


In [17]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)


array([0.96, 0.96, 0.94])

In [18]:
cross_val_score(SVC(gamma='auto',C = 25), iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=120),iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.94])